In [91]:
import pandas as pd
import numpy as np
import os
import math

In [92]:
#read dataset
df = pd.read_csv("CollegeBasketballPlayers2009-2021.csv")
df.head()

/var/folders/4_/jr_782k96kbcxx9ydbvttj4w0000gn/T/ipykernel_36385/2714199083.py:2: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("CollegeBasketballPlayers2009-2021.csv")

,player_name,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,Unnamed: 64,Unnamed: 65
0,DeAndrae Ross,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,1.6,...,-1.941150,0.1923,0.6154,0.8077,1.1923,0.3462,0.0385,3.8846,NaN,6.22026
1,Pooh Williams,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,3.8,...,-0.247934,0.6765,1.2647,1.9412,1.8235,0.4118,0.2353,5.9412,NaN,3.94375
2,Jesus Verdejo,South Florida,BE,27,72.0,96.2,21.8,45.7,47.98,2.1,...,-0.883163,0.6296,2.3333,2.9630,1.9630,0.4815,0.0000,12.1852,NaN,10.92680
3,Mike Hornbuckle,Pepperdine,WCC,30,44.5,97.7,16.0,53.6,53.69,4.1,...,-0.393459,0.7000,1.4333,2.1333,1.1000,0.5667,0.1333,4.9333,NaN,6.77427
4,Anthony Brown,Pacific,BW,33,56.2,96.5,22.0,52.8,54.31,8.3,...,-0.668318,1.4242,3.3030,4.7273,0.8485,0.4545,0.3333,7.5758,NaN,0.00000

In [93]:
min_minutes_played = 35

In [94]:
#remove all records where player played less than 5 minutes
df = pd.DataFrame(df[df['mp'] > min_minutes_played])
df

,player_name,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,Unnamed: 64,Unnamed: 65
22,Corey Lowe,Boston University,AE,29,84.8,103.6,27.5,53.5,54.68,2.1,...,-1.102900,0.6552,3.3793,4.0345,4.1379,1.2414,0.1379,17.1724,NaN,13.46890
33,Charles Jenkins,Hofstra,CAA,31,86.2,104.3,30.8,43.1,50.76,2.7,...,1.166500,0.9032,3.8387,4.7419,4.3226,1.4194,0.4516,19.5161,NaN,5.09412
51,Jeremy Wise,Southern Miss,CUSA,29,89.5,104.6,27.7,47.0,55.85,1.1,...,0.420674,0.3448,3.1379,3.4828,4.6207,1.3103,0.2759,16.6897,NaN,5.63586
53,Josh Akognon,Cal St. Fullerton,BW,31,89.4,107.9,30.6,50.5,54.91,1.8,...,-3.030870,0.5806,2.6774,3.2581,1.6129,1.0323,0.0323,23.8387,NaN,18.43630
79,Kenny Dawkins,Lamar,Slnd,21,71.7,96.5,23.4,44.7,51.03,1.2,...,-1.030810,0.3810,3.6190,4.0000,3.6190,1.2857,0.0476,14.4286,NaN,9.07908
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59436,Cam Mack,Prairie View A&M,SWAC,18,77.3,98.2,22.4,42.3,46.61,2.2,...,0.660344,0.7222,2.4444,3.1667,7.6667,2.6667,0.3333,11.1667,Pure PG,7.98495
59625,Cade Cunningham,Oklahoma St.,B12,27,78.0,104.1,28.6,51.6,57.46,2.3,...,2.536370,0.7037,5.4815,6.1852,3.4444,1.5926,0.7778,20.2222,Wing F,8.87260
60539,Jalen Moore,Oakland,Horz,30,91.5,105.2,28.9,44.4,51.93,0.8,...,-1.512280,0.2667,3.8667,4.1333,8.4000,1.6667,0.0667,17.9000,Pure PG,7.28338
60608,Darrion Trammell,Seattle,WAC,19,90.3,103.1,32.8,46.4,53.17,1.9,...,0.950771,0.6087,3.1739,3.7826,5.3478,1.9565,0.2609,20.4783,Pure PG,9.54500
60998,Terry Collins,Mississippi Valley St.,SWAC,21,76.8,83.7,22.2,46.1,48.70,2.0,...,-3.450760,0.6667,4.4762,5.1429,2.6190,1.2857,0.4762,12.2857,Combo G,10.40700

In [95]:
positions = df['Unnamed: 64']

In [96]:
df.to_csv('moreThan30.csv')

In [61]:
positions.unique()

array([nan, 'Wing F', 'Combo G', 'Scoring PG', 'Wing G', 'Pure PG',
       'PF/C', 'Stretch 4', 'C'], dtype=object)

In [62]:
#rename position column

df = df.rename({'Unnamed: 64': 'position'}, axis=1)

In [63]:
df['position'].unique()

array([nan, 'Wing F', 'Combo G', 'Scoring PG', 'Wing G', 'Pure PG',
       'PF/C', 'Stretch 4', 'C'], dtype=object)

In [64]:
#get all unique positions, remove null position
positions = []
for x in df['position'].unique():
    positions.append(x)
positions = positions[1:]
positions

['Wing F',
 'Combo G',
 'Scoring PG',
 'Wing G',
 'Pure PG',
 'PF/C',
 'Stretch 4',
 'C']

In [65]:
os.listdir('split_by_position')

['c.csv',
 'combo-g.csv',
 'pure-pg.csv',
 'wing-f.csv',
 'wing-g.csv',
 'scoring-pg.csv',
 'pf-c.csv',
 'stretch-4.csv']

In [12]:
#create new dataset of all nba players for each position
all_players = pd.read_csv('split_by_position/wing-g.csv')
nba_players = pd.DataFrame()
for i in range(all_players.shape[0]):
    if not np.isnan(all_players.iloc[i].pick):
        nba_players = nba_players.append(all_players.iloc[i], ignore_index=True)

/var/folders/4_/jr_782k96kbcxx9ydbvttj4w0000gn/T/ipykernel_36385/3995878693.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  nba_players = nba_players.append(all_players.iloc[i], ignore_index=True)

In [13]:
#write them to a .csv file
nba_players.to_csv('nba-wing-g.csv')